project:
  type: website
    
website:
  site-url: https://FabianZah.github.io/
  repo-url: https://github.com/FabianZah/FabianZah.github.io/
  title: "Fabian Zahnow"
  navbar:
    left:
      - text: "My research"
        href: index.qmd
      - text: "About me"
        href: about.qmd

format:
  html:
    theme: darkly
    css: styles.css
    toc: true

execute:
  freeze: auto
  
